services:
  db:
    image: postgres:16
    volumes:
      - ./pgdata/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gototravel_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
